### ISSUE TITLE
QmdpTest fails

### ISSUE THREAD

**Issue by dmaniloff** [dmaniloff/libpomdp#3]
setting problem to RockSample_7_8.POMDP in libpomdp.test.QmdpTest:

qmdp:
     [echo] Running QmdpTest
     [exec] PARSER: Parsing preamble...
     [exec] PARSER: Summary -> states 12545
     [exec]                 -> observations 2
     [exec]                 -> actions 13
     [exec] PARSER: Parsing starting state/belief...
     [exec] PARSER: Parsing parameters...
     [exec] PARSER: [DONE]
     [exec] Eval(0) = Inf
     [exec] == Iteration 0 ==
     [exec] Exception in thread "main" java.lang.IndexOutOfBoundsException: A.numColumns != x.size (2 != 12545)
     [exec]     at no.uib.cipr.matrix.AbstractMatrix.checkMultAdd(AbstractMatrix.java:173)
     [exec]     at no.uib.cipr.matrix.AbstractMatrix.multAdd(AbstractMatrix.java:159)
     [exec]     at no.uib.cipr.matrix.sparse.FlexCompColMatrix.multAdd(FlexCompColMatrix.java:114)
     [exec]     at no.uib.cipr.matrix.AbstractMatrix.mult(AbstractMatrix.java:151)
     [exec]     at libpomdp.common.CustomMatrix.mult(Unknown Source)
     [exec]     at libpomdp.common.std.PomdpStd.mdpValueUpdate(Unknown Source)
     [exec]     at libpomdp.solve.offline.heuristic.QmdpPolicyStd.iterate(Unknown Source)
     [exec]     at libpomdp.solve.Iteration.run(Unknown Source)
     [exec]     at libpomdp.test.QmdpTest.main(Unknown Source)
     [exec] Result: 1

**Comment by maray** [comment]
In which branch is this? I've already fixed this in my branch, but it will be hard to isolate. Just tell me in which branch and I will do the backport

**Comment by dmaniloff** [comment]
tested on branch 'diego' (former 'integration' branch)

**Comment by dmaniloff** [comment]
also tested on the 'maray' branch. same issue.

**Comment by maray** [comment]
Fixed in my branch, I've sent you a cherry-picked patch for yours.
